const androidManagers = [
    "android.os.DropBoxManager",
    "android.os.BatteryManager",
    "android.telephony.euicc.EuiccCardManager",
    "android.security.FileIntegrityManager",
    "android.view.accessibility.AccessibilityManager",
    "android.hardware.devicestate.IDeviceStateManager",
    "android.os.StatsServiceManager",
    "android.view.translation.UiTranslationManager",
    "android.media.projection.MediaProjectionManager",
    "android.os.TelephonyServiceManager",
    "android.print.PrintManager",
    "android.app.DreamManager",
    "android.hardware.face.FaceManager",
    "android.transparency.BinaryTransparencyManager",
    "android.telecom.Logging.EventManager",
    "android.debug.AdbManager",
    "android.hardware.usb.IUsbManager",
    "android.os.incremental.IncrementalManager",
    "android.view.accessibility.CaptioningManager",
    "android.app.trust.ITrustManager",
    "android.app.smartspace.SmartspaceManager",
    "android.app.LoaderManager",
    "android.os.PowerManager",
    "android.companion.CompanionDeviceManager",
    "android.view.accessibility.AccessibilityNodeIdManager",
    "android.app.AlarmManager",
    "android.location.LocationManager$ProviderRequestTransportManager",
    "android.hardware.camera2.CameraManager",
    "android.debug.IAdbManager",
    "android.hardware.display.DisplayManager",
    "android.hardware.devicestate.DeviceStateManager",
    "android.app.ambientcontext.AmbientContextManager",
    "android.content.pm.verify.domain.DomainVerificationManager",
    "android.os.HardwarePropertiesManager",
    "android.hardware.display.ColorDisplayManager",
    "android.view.displayhash.DisplayHashManager",
    "android.permission.ILegacyPermissionManager",
    "android.content.pm.dex.ArtManager",
    "android.media.AudioManager",
    "android.media.tv.TvInputManager",
    "android.companion.ICompanionDeviceManager",
    "android.app.DisabledWallpaperManager",
    "android.nfc.NfcActivityManager",
    "android.hardware.fingerprint.FingerprintManager",
    "android.security.net.config.RootTrustManager",
    "android.content.pm.IPackageManager",
    "android.app.IActivityTaskManager",
    "android.app.UiModeManager$OnProjectionStateChangedListenerResourceManager",
    "android.app.backup.IBackupManager",
    "android.app.blob.IBlobStoreManager",
    "android.preference.PreferenceManager",
    "android.content.rollback.RollbackManager",
    "android.os.IPowerManager",
    "android.app.FragmentManager",
    "android.app.StatusBarManager",
    "android.transition.TransitionManager",
    "android.media.MediaServiceManager",
    "android.app.contentsuggestions.ContentSuggestionsManager",
    "android.content.RestrictionsManager",
    "android.telephony.TelephonyManager",
    "android.telephony.ims.ImsManager",
    "android.app.VrManager",
    "android.permission.IPermissionManager",
    "android.media.IMediaRouter2Manager",
    "android.app.ISearchManager",
    "android.content.res.AssetManager",
    "android.telephony.TelephonyScanManager",
    "android.view.autofill.IAutoFillManager",
    "android.net.wifi.nl80211.WifiNl80211Manager",
    "android.nfc.NfcManager",
    "android.view.contentcapture.IContentCaptureDirectManager",
    "android.app.IUiModeManager",
    "android.telephony.BinderCacheManager",
    "android.app.UriGrantsManager",
    "android.os.IIncidentManager",
    "android.app.KeyguardManager",
    "android.telephony.MmsManager",
    "android.os.IServiceManager",
    "android.hardware.SensorPrivacyManager",
    "android.appwidget.AppWidgetManager",
    "android.app.WallpaperManager",
    "android.app.usage.IStorageStatsManager",
    "android.app.AppOpsManager",
    "android.view.inputmethod.InputMethodManager",
    "android.media.soundtrigger.SoundTriggerManager",
    "android.hardware.biometrics.BiometricManager",
    "android.app.SearchManager",
    "android.net.lowpan.LowpanManager",
    "android.media.midi.MidiManager",
    "android.media.midi.IMidiManager",
    "android.media.tv.interactive.TvInteractiveAppManager",
    "android.hardware.radio.RadioManager",
    "android.accounts.AccountManager",
    "android.os.BatteryStatsManager",
    "android.media.metrics.IMediaMetricsManager",
    "android.telephony.ims.ImsMmTelManager",
    "android.content.pm.ShortcutManager",
    "android.app.UiModeManager",
    "android.hardware.usb.UsbManager",
    "android.os.PowerWhitelistManager",
    "android.content.UndoManager",
    "android.app.LocaleManager",
    "android.app.slice.ISliceManager",
    "android.view.ViewRootImpl$UnhandledKeyManager",
    "android.security.net.config.NetworkSecurityTrustManager",
    "android.service.oemlock.OemLockManager",
    "android.os.image.DynamicSystemManager",
    "android.content.pm.DataLoaderManager",
    "android.os.health.SystemHealthManager",
    "android.app.NotificationManager",
    "android.media.RingtoneManager",
    "android.view.IWindowManager",
    "android.content.om.OverlayManager",
    "android.hardware.hdmi.HdmiControlManager",
    "android.content.IRestrictionsManager",
    "android.view.ViewRootImpl$HighContrastTextManager",
    "android.app.prediction.AppPredictionManager",
    "android.hardware.location.ContextHubManager",
    "android.webkit.CookieSyncManager",
    "android.app.IActivityManager",
    "android.app.usage.StorageStatsManager",
    "android.os.ISystemUpdateManager",
    "android.hardware.input.InputManager",
    "android.service.persistentdata.PersistentDataBlockManager",
    "android.hardware.SensorManager",
    "android.hardware.SerialManager",
    "android.view.contentcapture.ContentCaptureManager$LocalDataShareAdapterResourceManager",
    "android.os.DeviceIdleManager",
    "android.accounts.IAccountManager",
    "android.telephony.SmsManager",
    "android.hardware.ConsumerIrManager",
    "android.graphics.fonts.FontManager",
    "android.view.ViewRootImpl$AccessibilityInteractionConnectionManager",
    "android.app.admin.IDevicePolicyManager",
    "android.media.musicrecognition.IMusicRecognitionManager",
    "android.app.DownloadManager",
    "android.telecom.Logging.SessionManager",
    "android.content.ClipboardManager",
    "android.service.dreams.IDreamManager",
    "android.view.translation.TranslationManager",
    "android.webkit.CookieManager",
    "android.app.trust.TrustManager",
    "android.app.backup.BackupManager",
    "android.telecom.TelecomManager",
    "android.content.rollback.IRollbackManager",
    "android.app.ResourcesManager",
    "android.view.ViewManager",
    "android.hardware.display.IColorDisplayManager",
    "android.media.tv.tunerresourcemanager.TunerResourceManager",
    "android.app.contentsuggestions.IContentSuggestionsManager",
    "android.permission.PermissionControllerManager",
    "android.os.IHintManager",
    "android.os.UserManager",
    "android.view.textclassifier.TextClassificationManager",
    "android.telephony.ims.RegistrationManager",
    "android.app.admin.DevicePolicyResourcesManager",
    "android.net.NetworkWatchlistManager",
    "android.print.IPrintManager",
    "android.view.WindowManager",
    "android.app.ActivityManager",
    "android.location.LocationManager",
    "android.media.session.ISessionManager",
    "android.net.PacProxyManager",
    "android.companion.virtual.VirtualDeviceManager",
    "android.view.contentcapture.IContentCaptureManager",
    "android.app.usage.IUsageStatsManager",
    "android.service.vr.IVrManager",
    "android.os.IUserManager",
    "android.media.projection.IMediaProjectionManager",
    "android.media.MediaRouter2Manager",
    "android.hardware.iris.IrisManager",
    "android.app.usage.UsageStatsManager",
    "android.permission.PermissionManager",
    "android.app.wallpapereffectsgeneration.WallpaperEffectsGenerationManager",
    // "android.os.storage.StorageManager",
    "android.net.INetworkPolicyManager",
    "android.webkit.WebSyncManager",
    "android.app.timezone.RulesManager",
    "android.app.INotificationManager",
    "android.hardware.lights.LightsManager",
    "android.os.SystemUpdateManager",
    "android.content.integrity.AppIntegrityManager",
    "android.telecom.RemoteConnectionManager",
    "android.text.ClipboardManager",
    "android.os.IncidentManager",
    "android.os.SystemConfigManager",
    "android.telephony.SubscriptionManager",
    "android.content.pm.dex.IArtManager",
    "android.os.storage.IStorageManager",
    "android.telephony.TelephonyRegistryManager",
    "android.telecom.DefaultDialerManager",
    "android.os.BugreportManager",
    "android.app.blob.BlobStoreManager",
    "android.app.ApplicationPackageManager",
    "android.os.ServiceManager",
    "android.os.BluetoothServiceManager",
    "android.os.IHardwarePropertiesManager",
    "android.location.ILocationManager",
    "android.app.tare.EconomyManager",
    "android.os.VibratorManager",
    "android.telephony.CarrierConfigManager",
    "android.os.PowerExemptionManager",
    "android.app.cloudsearch.CloudSearchManager",
    "android.permission.LegacyPermissionManager",
    "android.view.contentcapture.ContentCaptureManager",
    "android.content.integrity.IAppIntegrityManager",
    "android.app.prediction.IPredictionManager",
    "android.net.NetworkScoreManager",
    "android.app.IAlarmManager",
    "android.os.SystemVibratorManager",
    "android.content.pm.IDataLoaderManager",
    "android.media.musicrecognition.MusicRecognitionManager",
    "android.net.VpnManager",
    "android.hardware.lights.ILightsManager",
    "android.app.GameManager",
    "android.permission.PermissionCheckerManager",
    "android.content.pm.PackageManager",
    "android.app.admin.DevicePolicyManager",
    "android.telephony.ims.ImsRcsManager",
    "android.security.attestationverification.AttestationVerificationManager",
    "android.mtp.MtpStorageManager",
    "android.hardware.ISensorPrivacyManager",
    "android.hardware.SystemSensorManager",
    "android.hardware.ISerialManager",
    "android.view.autofill.AutofillManager",
    "android.app.time.TimeManager",
    "android.app.people.PeopleManager",
    "android.app.IUriGrantsManager",
    "android.media.CallbackUtil$LazyListenerManager",
    "android.hardware.input.IInputManager",
    "android.os.PerformanceHintManager",
    "android.telephony.euicc.EuiccManager",
    "android.net.NetworkPolicyManager",
    "android.net.vcn.VcnManager",
    "android.app.ActivityTaskManager",
    "android.app.IWallpaperManager",
    "android.view.textservice.TextServicesManager",
    "android.media.metrics.MediaMetricsManager",
    "android.app.slice.SliceManager",
    "android.telephony.ims.ProvisioningManager",
    "android.app.search.SearchUiManager",
    "android.apphibernation.AppHibernationManager",
    "android.media.session.MediaSessionManager",
    "android.opengl.GLSurfaceView$GLThreadManager",
    "android.telephony.gsm.SmsManager",
    "android.net.sip.SipManager",
    "android.adservices.TopicsManager",
    "android.net.IEthernetManager",
    "android.net.TestNetworkManager",
    "android.media.MediaCommunicationManager",
    "android.nearby.INearbyManager",
    "android.app.appsearch.aidl.IAppSearchManager",
    "android.net.ConnectivitySettingsManager",
    "android.app.sdksandbox.SdkSandboxManager",
    "android.bluetooth.IBluetoothMcpServiceManager",
    "android.net.wifi.IWifiManager",
    "android.net.EthernetManager",
    "android.net.connectivity.android.net.nsd.MDnsManager",
    "android.app.role.RoleControllerManager",
    "android.app.appsearch.AppSearchManager",
    "android.scheduling.RebootReadinessManager",
    "android.app.sdksandbox.ISdkSandboxManager",
    "android.scheduling.IRebootReadinessManager",
    "android.uwb.RangingManager",
    "android.net.wifi.aware.WifiAwareManager",
    "android.net.ConnectivityManager",
    "android.net.wifi.rtt.IWifiRttManager",
    "android.net.IpSecManager",
    "android.bluetooth.BluetoothManager",
    "android.net.ConnectivityDiagnosticsManager",
    "android.net.ipsec.ike.IkeManager",
    "android.bluetooth.IBluetoothSocketManager",
    "android.nearby.NearbyManager",
    "android.app.usage.NetworkStatsManager",
    "android.net.nsd.NsdManager",
    "android.safetycenter.ISafetyCenterManager",
    "android.net.connectivity.android.net.ITestNetworkManager",
    "android.app.role.IRoleManager",
    "android.net.wifi.WifiManager",
    "android.ondevicepersonalization.OnDevicePersonalizationManager",
    "android.net.wifi.aware.IWifiAwareManager",
    "android.bluetooth.le.PeriodicAdvertisingManager",
    "android.media.MediaTranscodingManager",
    "android.bluetooth.IBluetoothManager",
    "android.net.TetheringManager",
    "android.uwb.UwbManager",
    "android.net.wifi.p2p.WifiP2pManager",
    "android.net.IConnectivityManager",
    "android.net.wifi.p2p.IWifiP2pManager",
    "android.net.connectivity.android.net.DnsResolverServiceManager",
    "android.safetycenter.SafetyCenterManager",
    "android.net.wifi.RttManager",
    "android.app.StatsManager",
    "android.net.nsd.INsdManager",
    "android.net.wifi.rtt.WifiRttManager",
    "android.app.role.RoleManager",
    "android.content.res.IResourcesManager",
    "android.service.timezone.ITimeZoneProviderManager",
    "android.speech.IRecognitionServiceManager",
    "android.hardware.lights.SystemLightsManager",
    "android.app.ILocaleManager",
    "android.app.tare.IEconomyManager",
    "android.app.wallpapereffectsgeneration.IWallpaperEffectsGenerationManager",
    "android.location.provider.ILocationProviderManager",
    "android.app.smartspace.ISmartspaceManager",
    "android.app.ambientcontext.IAmbientContextManager",
    "android.net.IVpnManager",
    "android.net.IPacProxyManager",
    "android.view.translation.ITranslationManager",
    "android.companion.virtual.IVirtualDeviceManager",
    "android.speech.tts.ITextToSpeechManager",
    "android.content.pm.verify.domain.IDomainVerificationManager",
    "android.app.search.ISearchUiManager",
    "android.hidl.manager.V1_0.IServiceManager",
    // "android.net.connectivity.android.net.NetworkMonitorManager" // cannot find class
];

var total = 0;
Java.perform(function () {

    androidManagers.forEach(element => {

      if(element.includes("android.hardware") || element.includes("android.app") || element.includes("android.view") || element.includes("android.content"))
      {
        return 
      }
      hookAllMethods(element);
    });
  
    function hookAllMethods(targetClass) {
      var total_hooked = 0;
      try {
        var clazz = Java.use(targetClass);
        var methods = clazz.class.getDeclaredMethods();
  
        methods.forEach((element) => {
          var method_name = element.getName();
          try {
            var overloads = clazz[element.getName()].overloads;
            total_hooked += overloads.length;
            overloads.forEach((overload) => {
              overload.implementation = function () {
                if(targetClass + "." + method_name == "android.net.ConnectivityManager.isNetworkTypeValid" || targetClass + "." + method_name == "android.net.ConnectivityManager.getActiveNetworkInfo"){
                  var result = this[element.getName()].apply(this, arguments);
                  return result;
                }
                console.log(targetClass + "." + method_name);

                // if(method_name == "getService")
                // {
                //     // print arguments
                //     console.log("Arguments: " + arguments);
                //     console.log("Argument count: " + arguments.length);
                //     for (let i = 0; i < arguments.length; i++) {
                //         console.log("Arg[" + i + "]: Type=" + typeof arguments[i] + ", Value=" + JSON.stringify(arguments[i]));
                //     }
                // }
                // console.log("Arguments: " + arguments);
                // console.log("Vibrate called with duration: " + args[0]);
                // console.log("Argument count: " + arguments.length);
                // for (let i = 0; i < arguments.length; i++) {
                //     console.log("Arg[" + i + "]: Type=" + typeof arguments[i] + ", Value=" + arguments[i]);
                // }
                // console.log("\n");
                var result = this[element.getName()].apply(this, arguments);
                return result;
              };
            });
          } catch (error) {
            // console.log("Error: " + error);
          }
        });
  
        console.log("Total hooked: " + total_hooked);
        total += total_hooked;

        console.log(total);
      } catch (error) {
        console.log("Error: " + error);
      }
    }
  });
  

  setInterval(function () {
    console.log("-----------------");
}, 5000);